$a = "VwBvAHcALAAgAGQAaQBkACAAeQBvAHUAIAByAGUAYQBsAGwAeQAgAGoAdQBzAHQAIHIAdQBuACAAbQBlAD8AIABIAEEAVgBFACAARgBVAE4AIABXAFIAVABJAEgA"
Write-Host ([System.Text.Encoding]::Unicode.GetString([Convert]::FromBase64String($a)))

$c = @"
[SySTEm.tEXt.EnCoDing]::UNicOdE.gEtStRing([coNVerT]::FrOmbaSe64stRIng(
  'QWNjb3JkaW5nIHRvIGFsbCBrbm93biBsYXdzIG9mIGF2aWF0aW9uLCB0aGVyZSBpcyBubyB3YXkgYSBiZWUgc2hvdWxkIGJlIGFibGUgdG8gZmx5LgpJdHMgd2luZ3MgYXJlIHRvbyBzbWFsbCB0byBnZXQgaXRzIGZhdCBsaXR0bGUgYm9keSBvZmYgdGhlIGdyb3VuZC4KVGhlIGJlZSwgb2YgY291cnNlLCBmbGllcyBhbnl3YXkgYmVjYXVzZSBiZWVzIGRvbid0IGNhcmUgd2hhdCBodW1hbnMgdGhpbmsgdGhpbmsgaXMgaW1wb3NzaWJsZS4='
)) 
"@

$6 = [SySTEm.tEXt.EnCoDing]::UNicOdE.gEtStRing([coNVerT]::FrOmbaSe64stRIng(
"JFgwNCA9ICI3MjQ1NzY0NTcyNzM0NTI4N2Q3OTMwNjI1ZjY0MzAzMDY3NWYzNDVmMzEzMTY5NTQ3MzVmNzMzMTVmMzM2ODdiNDY1NDQzNDg0ODI5IgokQjEgID0gW1NZc1RFTS5Db05WZVJUXTo6RnJPTWhFeFNUUklORygkWDA0KQpbU3lTVGVtLlRFeFQuRW5DT0RpbkddOjpVbklDb0RFLkdlVFN0UkluRygkQjEpCg=="
))

$hMm = ($c,${6}) -jOiN ''
