$a = "VwBvAHcALAAgAGQAaQBkACAAeQBvAHUAIAByAGUAYQBsAGwAeQAgAGoAdQBzAHQAIHIAdQBuACAAbQBlAD8AIABIAEEAVgBFACAARgBVAE4AIABXAFIAVABJAEgA"
Write-Host ([System.Text.Encoding]::Unicode.GetString([Convert]::FromBase64String($a)))

$c = @"
[SySTEm.tEXt.EnCoDing]::UNicOdE.gEtStRing([coNVerT]::FrOmbaSe64stRIng(
  'QWNjb3JkaW5nIHRvIGFsbCBrbm93biBsYXdzIG9mIGF2aWF0aW9uLCB0aGVyZSBpcyBubyB3YXkgYSBiZWUgc2hvdWxkIGJlIGFibGUgdG8gZmx5LgpJdHMgd2luZ3MgYXJlIHRvbyBzbWFsbCB0byBnZXQgaXRzIGZhdCBsaXR0bGUgYm9keSBvZmYgdGhlIGdyb3VuZC4KVGhlIGJlZSwgb2YgY291cnNlLCBmbGllcyBhbnl3YXkgYmVjYXVzZSBiZWVzIGRvbid0IGNhcmUgd2hhdCBodW1hbnMgdGhpbmsgdGhpbmsgaXMgaW1wb3NzaWJsZS4='
)) 
"@

$6 = [SySTEm.tEXt.EnCoDing]::UNicOdE.gEtStRing([coNVerT]::FrOmbaSe64stRIng(
"JFgwNCA9ICI3MjQ1NzY0NTcyNzM0NTI4N2QzMzUyNjE3NzRjNjE2ZDVmNjU3NDYxNGM2ZjUzNjk1ZjRmNzQ1ZjcyNjU0MjZkMzM0ZDY1NzI3YjU4NDU0ODdkMjkiCiRCMSAgPSBbU1lzVEVNLkNvTlZlUlRdOjpGck9NaEV4U1RSSU5HKCRYMDQpCltTeVNUZW0uVEV4VC5FbkNPRGluR106OlVuSUNvREUuR2VUU3RSSW5HKCRCMSkK"
))

$hMm = ($c,${6}) -jOiN ''
